server:
  port: 8089
  ##context-path: /dev-api/testdev
  context-path: /

logging:
  level:
    com:
      cxnb:
        mapper: debug
##
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxnb.entity

spring:
  #  mvc:
  #    static-path-pattern: /**
  # resources:
  #static-locations: classpath:/templates/
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: cms_123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.160.146:4306/airdrop?useSSL=false&characterEncoding=utf-8
    username: cms

    #druid
    druid:

      connection-properties: clientEncoding=UTF-8

      initial-size: 1

      max-active: 20

      max-wait: 60000

      min-idle: 3

      remove-abandoned: true

      remove-abandoned-timeout: 180

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    suffix: .html
    content-type: text/html

  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/assets/images/,,file:${index.html}

## hecochain contract data info
heco:
  environment-url: https://http-mainnet-node.huobichain.com
  pk: "0x2a0fcdde6f254758ce1e0bfd2ca36ec8ec3ee6b770d095723f82e98bf292120f"
  pub: "0x735d997E7F4ED2E5Ae564647d777A41d666a3c27"
  apikey: XDPZWVYIT4W21YY3DZNWBUUDQB1X6S55MY
  toppath: D:\ajava\coin\cxnb-new\src\main\resources\tokenAddress.txt
  tokenpath: D:\ajava\coin\cxnb-new\src\main\resources\topAccountAddress.txt
  token:
    total: 100000000
    decimal: 9
    name: mob
    contract-address: "0x66dD43C03fa91aBeCb8F4EE2F7F34de9ed88eB26"
    share: 0.06
    airdrop: 1000

   ## airdropmin: 100
    ##airdropmax: 1000
